---
title: "构建生产级App: golem + shiny"
output: 
  github_document
  toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 参考书籍

- [工程生产级Shiny应用程序](https://engineering-shiny.org/index.html)


## 初始化golem + shiny

```{r eval=FALSE}
golem::fill_desc(
  pkg_name = "golemShiny",
  pkg_title = "Golem+Shiny",
  pkg_description = "Learning golem and shiny",
  authors = person(
    given = "Donghui",
    family = "Xia",
    email = "dhxia@snut.edu.cn",
    role = c("aut", "cre")
  ),
  repo_url = NULL,
  pkg_version = "0.0.0.9000",
  set_options = TRUE
)

# You can set another license here
usethis::use_mit_license( name = "Golem User" )
# Add a README, Code of Conduct, lifecycle badge and NEWS.md
# file to your application
usethis::use_readme_rmd( open = FALSE )
usethis::use_code_of_conduct()
usethis::use_lifecycle_badge( "Experimental" )
usethis::use_news_md( open = FALSE )

usethis::use_git()

golem::use_recommended_tests()

```


## shinipsum

```{r eval=FALSE}
library(shinipsum)
library(ggplot2)

# 随机图
random_ggplot() + 
  labs(title = "Random plot") 
```

### 第1个shiny程序

```{r eval=FALSE}
library(shiny)
library(shinipsum)
library(DT)

ui <- fluidPage(
  h2("A Random DT"),
  DTOutput("data_table"),
  h2("A Random Plot"),
  plotOutput("plot"),
  h2("A Random Text"),
  tableOutput("text")
)

server <- function(input, output, session) {
  output$data_table <- DT::renderDT({
    random_DT(5, 5)
  })
  output$plot <- renderPlot({
    random_ggplot()
  })
  output$text <- renderText({
    random_text(nwords = 50)
  })
}
shinyApp(ui, server)
```


